# Generated by Django 2.2.14 on 2020-07-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.IntegerField(default=1)),
                ('engenhocas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Super',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(choices=[('H', 'Heroico'), ('N', 'Neutro'), ('V', 'Vilanesco')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('heroico', models.CharField(max_length=200)),
                ('neutro', models.CharField(max_length=200)),
                ('vilanesco', models.CharField(max_length=200)),
                ('territorio', models.CharField(blank=True, choices=[('H', 'Heroico'), ('N', 'Neutro'), ('V', 'Vilanesco')], default='N', max_length=1)),
                ('visitors', models.ManyToManyField(to='autropolis_map.Super')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
