# Generated by Django 2.2.14 on 2020-07-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autropolis_map', '0003_local_especial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='super',
            options={'ordering': ['nome']},
        ),
        migrations.RenameField(
            model_name='super',
            old_name='name',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='local',
            name='especial',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
