# Generated by Django 2.2.14 on 2020-07-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autropolis_map', '0004_auto_20200724_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='especial',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='local',
            name='heroico',
            field=models.CharField(default='Nada', max_length=200),
        ),
        migrations.AlterField(
            model_name='local',
            name='visitors',
            field=models.ManyToManyField(blank=True, to='autropolis_map.Super'),
        ),
    ]
