# Generated by Django 2.2.14 on 2020-07-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autropolis_map', '0005_auto_20200725_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='overrider',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
