# Generated by Django 2.2.14 on 2020-07-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autropolis_map', '0007_auto_20200727_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fase',
            field=models.CharField(choices=[('1', 'Preparação'), ('2', 'Planejamento'), ('3', 'Realocação'), ('4', 'Combate'), ('5', 'Resolução')], default='1', max_length=100),
        ),
    ]
