# Generated by Django 2.2.14 on 2020-07-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autropolis_map', '0008_game_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='super',
            name='bravado',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='super',
            name='combate',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='super',
            name='ferimentos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='super',
            name='prestigio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='super',
            name='reflexos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='super',
            name='saude',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='game',
            name='fase',
            field=models.CharField(choices=[('Preparação', 'Preparação'), ('Planejamento', 'Planejamento'), ('Realocação', 'Realocação'), ('Combate', 'Combate'), ('Resolução', 'Resolução')], default='Preparação', max_length=100),
        ),
    ]
